ezpublish:
    system:
        default:
            image_variations:
                # dedicated to images embedded in the blog_post body
                blog_post_full_width:
                    reference: ~
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [800] }
                blog_post_full_width_lightbox:
                    reference: ~
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [800] }
                blog_author:
                    reference: ~
                    filters:
                        - { name: geometry/scaleexact, params: [60, 60] }
                blog_post_author:
                    reference: ~
                    filters:
                        - { name: geometry/scaleexact, params: [80, 80] }
                blog_thumbnail:
                    reference: ~
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [710] }
liip_imagine:
    driver: imagick
    filter_sets:
        blog_thumbnail: &default
            png_compression_level: '%images.default_png_compression_level%'
            jpeg_quality: '%images.default_jpeg_quality%'
        blog_author:
            *default
        blog_post_author:
            *default
        blog_thumbnail:
            *default
