login:
    path: /login
    defaults: { _controller: ezpublish.security.controller:loginAction }

login_check:
    path: /login_check

logout:
    path: /logout

kernel.internal:
    resource: '@EzPublishCoreBundle/Resources/config/routing/internal.yml'

kernel.rest:
    resource: '@EzPublishRestBundle/Resources/config/routing.yml'
    prefix: '%ezpublish_rest.path_prefix%'

kernel.rest.options:
    resource: '@EzPublishRestBundle/Resources/config/routing.yml'
    prefix: '%ezpublish_rest.path_prefix%'
    type: rest_options

ezplatform.admin_ui:
    resource: '@EzPlatformAdminUiBundle/Resources/config/routing.yml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'

_ezplatformRepositoryFormsRoutes:
    resource: '@EzSystemsRepositoryFormsBundle/Resources/config/routing.yml'

fos.js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

# BLOG
_ezplatform_blog_ajax:
    path: /ezplatform/blog/load/page/{page}/{order}
    defaults: { _controller: app.controller.blog:showBlogPostsAction }
    methods:  [GET]
    requirements:
        "page": '\d+'


# BUNDLES LIST
_ezplatform_bundles_list:
    path: /Bundles/{page}/{order}/{searchText}
    defaults: { _controller: app.controller.bundle:showBundlesListAction, page: 1, order: 'default', searchText: '' }
    methods: [GET]
    requirements:
        "order": 'default|latestUpdate|stars|downloads'

_ezplatform_bundles_search_init:
    path: /Bundles/search/
    defaults: { _controller: app.controller.bundle:searchBundlesAction, page: 1, order: 'default' }
    methods: [POST]
    requirements:
        "order": 'default|latestUpdate|stars|downloads'

_ezplatform_bundles_search:
    path: /Bundles/search/{searchText}/{page}/{order}
    defaults: { _controller: app.controller.bundle:showBundlesListAction, page: 1, order: 'default', searchText: '' }
    methods: [GET, POST]

# TAGS
_ezplatform_tag_related_list_ajax:
    path: /ezplatform/tag/{tagId}/related/page/{page}/{order}
    defaults: { _controller: app.controller.tag:getTagRelatedContentAction }
    methods: [GET]
    requirements:
        "tagId": '\d+'
        "page": '\d+'
        "order": 'default'

_eztagsRoutes:
    resource: '@NetgenTagsBundle/Resources/config/routing.yml'

# Custom redirection from /ez to /admin, feel free to adjust to your needs or remove if you don't need it
platform1_admin_route:
    path: /ez
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /admin
        permanent: true
